### ISSUE TITLE
Dependency of Gulp 3.9.1 causes error in Node 10

### ISSUE THREAD

**Issue by alexweissman** [alexweissman/UserFrosting#882] opened 2018-05-10 14:22 UTC
There is a problem with `natives@1.1.0` that is resolved by manually switching over to `natives@1.1.3`. See https://forums.userfrosting.com/t/upgrade-to-node-v10-generates-errors/281:

```
> gulp bower-install

gulp[5156]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [gulp]
 2: 0x557220a7229b [gulp]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
 5: 0x557220c7ce97 [gulp]
 6: 0x557220c7d68f [gulp]
 7: 0xc1f1ae0427d
```

`npm ls` shows the relevant dependency trace:

```
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ graceful-fs@3.0.11
│   │ └── natives@1.1.0
```

So, it seems like we are accumulating more and more problems related to Gulp 3.9.1.

**Comment by linkhousemedia** [comment] 2018-05-10 20:08
Per @alexweissman, I have used a workaround and I've confirmed it worked. 

Add `"natives": "^1.1.3"` to `build/package.json` in the `devDependencies` property.

**Comment by Silic0nS0ldier** [comment] 2018-05-11 01:08
I'd wager that the offending dependency is still hidden away but not used. Likely the addition of the dependency gives whatever is using it a newer version to use (that doesn't conflict with its semver range). Probably a dependency wanting `~1.0.0` (of similar) somewhere in the dependency tree.

Of course, its entirely plausible a bug in NPM is causing this to resolve to an older version. Wouldn't be the first time. Hard to say without looking further though.

**Comment by lcharette** [comment] 2018-05-11 23:47
I tried to replicate any issue with assets on a fresh Homestead box and everything seems to work fine. Fresh UF master clone, tried with node 8 and 10.1.0

When running `php bakery build-assets -c`, everything works as it should out of the box for me. Might need to run `php bakery build-assets -f -c` if you already loaded some assets to force refresh the whole assets dir ? It would [delete the lock file and force update everything](https://github.com/gulpjs/gulp/issues/2162#issuecomment-384885950), which might not be a desired result, but in UF case, shouldn't matter (?).

I also checked the dependencies tree in `package-lock.json` and looks like `graceful-fs` is the only one requiring `natives`. So if it's still an issue with some of you, I guess we could do as @linkhousemedia said and add `"natives": "^1.1.3"` to our `build/package.json`, which seems to be [a recommended fix](https://github.com/gulpjs/gulp/issues/2162#issuecomment-385197164).

**Comment by alexweissman** [comment] 2018-05-13 21:02
I tried setting up a fresh install of UF with Node 7.  Running `npm ls | grep natives` in `build` shows that `natives@1.1.2` was installed as a part of the dependency graph.

When I upgraded to Node 10 and then ran `build-assets` again (with or without the `-f` flag), I saw the same error that @linkhousemedia was getting.

Deleting `build/node_modules` and `build/package-lock.json`, and then rerunning the `build-assets` command seemed to successfully install `natives@1.1.3` and thus resolve the compatibility errors. However, as the issue that @lcharette found suggests, you might not want to do this in a production scenario.

It would appear that `build-assets -f` runs the [`uf-clean` npm task](https://github.com/userfrosting/UserFrosting/blob/master/build/gulpfile.js#L175-L183), but this doesn't actually have anything to do with npm packages. `uf-clean` simply deletes the installed Bower packages from Sprinkles' `assets/vendor` directories, as well as compiled assets and the compiled asset bundle config file.

It's also worth noting that Node 10 is not yet officially recommended on the Node.js website - rather, as the LTS version, 8.11.1 is recommended for most users.

My takeaways from this issue are as follows:

- We could add `natives@1.1.3` to the UF `build/package.json` file, but I don't know how that will play with older versions of UF. Since it's not a direct dependency of UF, I'm reluctant to add it as an official dependency just to fix this one, uncommon error scenario.
- We should consider factoring the `build-assets` Bakery command into multiple subcommands (perhaps `build-assets:npm, `build-assets:install`, and `build-assets:compile`) with a flag that would let users clear the actual _npm_ cache and/or delete the _npm_ package lock file;
- This doesn't appear to be an issue in Node 8, the current LTS version. Furthermore, when I install UF on a fresh Vagrant box with Node 8, it seems to correctly install `natives@1.1.3`. So, this may only be an issue with Node <=7.
- The Gulp tasks are poorly named (`uf-clean` vs `uf-assets-clean`, etc). We should give them more intelligible names going forward.
- Overall, this demonstrates the fragility of the dependency graph. A "distribution repo", with all Composer, npm, and asset packages pre-installed, would help to avoid scaring away newbies who run into these sorts of issues as part of their first encounter with UF.

**Comment by Silic0nS0ldier** [comment] 2018-11-14 06:42
Work that will hopefully land in 4.2 should push us up to gulp v4 which will resolve the issue. As for the 4.1 line, adding the newer version of natives seems to resolve this reliably enough so I'll see about getting it into a hotfix.

**Comment by zhangshuzhen** [comment] 2018-12-18 05:41
delete yarn.lock and node_modules，use yarn command reinstall solve my problem.

**Comment by Silic0nS0ldier** [comment] 2018-12-21 03:05
@zhangshuzhen Guessing you were using Yarn over npm. Effect is the same, it forced the package manager to completely rebuild the dependency tree. Does hint at something weird happening in the package managers though, because they should be able to resolve this problem themselves.

Changes mentioned before have landed in `develop`, so they are slatted for release in 4.2.

**Closed as completed** 2019-01-11 10:28 UTC
Labels: compatibility, assets
