### ISSUE TITLE
Theme change error

### ISSUE THREAD

**Issue by panchtox** [alexweissman/UserFrosting#463] opened 2015-11-11 15:34 UTC
Hi, I've tried to change the theme from 'default' to 'nyx' and after that, every request returned error:
`[Wed Nov 11 09:22:27.592280 2015] [:error] [pid 97747] [client 127.0.0.1:53593] Error in /Library/WebServer/Documents/#########/userfrosting/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 215: Unable to find template "dashboard.twig" (looked into: /Library/WebServer/Documents/#########/userfrosting/templates/themes/root, /Library/WebServer/Documents/#########/userfrosting/templates/themes/nyx)., referer: http://foo.example.com/public/account/login`
Only after changing 'default_theme' value in the database configuration table again to 'default' I could return to a working system.

**Comment by alexweissman** [comment] 2015-11-11 16:16
I have been able to reproduce this problem.  I'll look into it.  Btw, are you sure you want to change the **default** theme?  Maybe you are just trying to change the theme for a particular user or group?

**Comment by panchtox** [comment] 2015-11-11 16:32
Hi, thanks. I don't understand the question very well. I'm trying to change the default site theme in the site configuration. Below the textbox says 'The default template theme to use for unauthenticated users'.

**Comment by alexweissman** [comment] 2015-11-11 17:49
Ok, yes then you are doing it correctly.  The problem is that the other themes do not implement all of the page templates, so they should fall back to `default` (the theme actually named "default").  I will fix this.

**Comment by alexweissman** [comment] 2015-11-13 00:06
Alright, fixed in https://github.com/alexweissman/UserFrosting/commit/8310c13890530f0eb75f13e104fff2fad61315c9

**Closed by alexweissman** 2015-11-13 00:06 UTC
Labels: bug

**Comment by panchtox** [comment] 2015-11-13 12:19
Tks!
