### ISSUE TITLE
User Sessions Dropping

### ISSUE THREAD

**Issue by ebrightTP** [alexweissman/UserFrosting#228] opened 2015-02-06 22:33 UTC
I'm having an error I'm having trouble reproducing, and I'm looking for suggestions for how to diagnose.  
It seems users sessions are randomly expiring on our site.  
I have no idea where to start on this error.  
session.save_path is currently set to /tmp.  Might that have something to do with it?

**Comment by alexweissman** [comment] 2015-02-06 23:23
I actually have that same problem on my sites that use UF.  I tried changing the expiration time, but it doesn't seem to help all that much.  

Your suggestion is worth looking into.  Are you also using XAMPP?

**Comment by alexweissman** [comment] 2015-02-06 23:26
This SO question might be worth looking in to: https://stackoverflow.com/questions/13239866/php-session-expiring-quickly-and-randomly?rq=1

If you can get it to work, make a pull request ;-)

**Comment by KevinC0** [comment] 2015-03-05 23:35
Hi, 

My session are expiring (well, users have to log in one again) after about 30 minutes in spite of a session cookie with a 60 days lifetime. It seems that the cookie is properly set (domain, duration, ...). 

Any updated status regarding this issue? 

FYI, it seems that the issue is worst since I'm using subdomains on my site. My subdomain is properly defined in the session_set_cookie_params function. 

I was wondering if something like http://stackoverflow.com/questions/6360093/how-to-set-lifetime-of-session could be useful. 

Best, 

Kevin

**Comment by alexweissman** [comment] 2015-03-06 01:06
Yeah, I still haven't been able to figure out a solution to this issue either :-/  Have you worked with any other PHP applications on your server that have this problem?  I'm not sure if it's something that needs to be configured outside of UF (such as in `php.ini`) or what.

I'm trying to reimplement UF with [Slim](http://www.slimframework.com/), which may or may not solve this issue.  I'm still not exactly sure how Slim interacts with PHP native sessions.

**Comment by r3wt** [comment] 2015-03-06 01:40
http://stackoverflow.com/questions/1327351/session-should-never-expire-by-itself

The accepted answer in this post can shed some light on it. alot of applications will use a cookie instead of sessions, and retrieve the user info on every run of the  application. i'm not a big fan of that but i believe UF doesn't store $loggedInUser in a session anyway(or does it?)

**Comment by r3wt** [comment] 2015-03-06 01:44
what i do personally, is a set interval function loop that runs every minute. it calls an ajax request to an endpoint, say `keepalive.php` for example. i use an hmac signed token hash to authenticate the request. i copy the session, destroy it, regenerate the id then save the new session. this allows users to go in active on my site but as long as the browser is open, their session will remain active. else it will expire. to catch this case, i store a secondary cookie that is good for 1 week. i store this cookie in the database, then when one of these cookies is encountered for a user that is not logged in, the users info is loaded from the database and the session is restored. this type of action is also hmac signed with a cookie that holds the last hmac token, preventing session hijacking through bruteforce.

**Comment by r3wt** [comment] 2015-03-06 01:46
@alexweissman is it safe for me to fork UF and fix this behavior?

**Comment by alexweissman** [comment] 2015-03-11 15:50
@KevinC0, this might be caused by having multiple different PHP applications running on your server.  In that case, you can also try setting a custom session path.  See https://stackoverflow.com/questions/3476538/php-sessions-timing-out-too-quickly.

> Random expiration is a classical symptom of session data directory shared by several applications: the one with the shortest session.gc_maxlifetime time is likely to remove data from other applications.

**Comment by rdmiller** [comment] 2015-03-29 03:28
I'm having the same problem on a fresh AWS EC2 instance.  I'm pretty sure it's PHPMyAdmin's 1440 second (24 min) setting that is the culprit re @alexweissman comment above.

**Comment by KevinC0** [comment] 2015-03-30 12:20
Finally, I stopped working on a mechanism that keeps the session alive: sessions have to expire quickly. Instead, I automatically re-log the user once the session has expired; more explanations below: 

   - I store a unique session_id and session_id hash in 2 separate cookies and in a dedicated mysql table called uf_sessions
   - Once the session expires, I have a look a the cookies and compare the information to the one stored in the uf_sessions table; if I have match, I log the user automatically and update the DB information with the new sessions info (and related hash)

In the end, once the cookie has expires (2 months in my case), user has to log in once again. It just works!

**Comment by ebrightTP** [comment] 2015-04-01 16:19
Awesome!  That sounds like it should work perfectly.  

Do you have any sample code, or have you left it as an exercise for the reader? ;)

**Comment by alexweissman** [comment] 2015-04-01 21:16
[Database-driven sessions](https://brennydoogles.wordpress.com/2011/09/06/taking-control-of-your-php-sessions-using-database-sessions/) are definitely a thing.  You might want to consider checking out [`session_set_save_handler`](http://php.net/manual/en/function.session-set-save-handler.php), which could automate the process of updating the DB.

But, I'm still not convinced that this is necessary for permanent sessions.  As @rdmiller points out, this could simply be a problem with the way certain platforms (like phpmyadmin) are pre-configured.

**Comment by alexweissman** [comment] 2015-04-01 21:34
@rdmiller, does phpMyAdmin's `LoginCookieValidity` setting applies to all sessions, or just sessions for actually logging into phpMyAdmin?

**Comment by alexweissman** [comment] 2015-04-01 21:40
Actually, I am starting to think that what we are really talking about is a "remember me" feature: https://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website

It seems like @KevinC0 is basically doing what is recommended in the top answer to this question.  But, rather than reinventing the wheel, is there a library that already does this?

**Comment by alexweissman** [comment] 2015-05-26 16:44
Let's keep this one open.  Session expiration is a major issue that we need to deal with at some point in 0.3.0.

**Comment by alexweissman** [comment] 2015-07-26 19:59
I have now added "remember me" functionality to the current `dev` branch, which implements database-driven "improved persistent sessions".

**Comment by alexweissman** [comment] 2015-09-03 17:08
"Remember me" will be released with v0.3.1.

**Comment by alexweissman** [comment] 2015-10-30 00:16
Implemented in 0.3.1.  Huzzah!

**Closed by alexweissman** 2015-10-30 00:16 UTC
Labels: 0.3.1 milestone, feature request, user experience
